---
new_page_extension: md
auto_deploy: false
admin_path: blog/.vuepress/public/admin
webhook_url: https://api.stackbit.com/project/5e9449a76a74910012178fa8/webhook/forestry
sections:
- type: document
  path: blog/.vuepress/data/config.json
  label: Config
  templates:
  - config
- type: document
  path: blog/index.md
  label: Home
  templates:
  - home
- type: directory
  path: blog
  label: Page
  create: all
  match: "**/*.md"
  exclude: "{index.md,posts/**/*,.vuewpress/**/*,index.md}"
  templates:
  - page
- type: directory
  path: blog/posts
  label: Post
  create: all
  match: "**/*.md"
  templates:
  - post
upload_dir: blog/.vuepress/public/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
